FROM node:14-alpine as build

# Create app directory
WORKDIR /srv/app

# Install app build dependencies
COPY package*.json ./
RUN npm install

# Compile project
COPY src src
COPY tsconfig.json ./
RUN npm run build

FROM node:14-alpine

# Add sqlite package
RUN apk add sqlite

# Create app directory
WORKDIR /srv/app

# Install production dependencies
COPY package*.json ./
RUN npm install --only=prod

COPY --from=build /srv/app/dist ./dist

# Run server
CMD [ "npm", "start" ]